service: logging-monitoring

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  generate:
    handler: handler.generate
    events:
      - http:
          path: generate/{number}
          method: get

  logProcessor:
    handler: logProcessor.handler
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "ses:*"
        Resource: "*"

plugins:
  - serverless-iam-roles-per-function
